name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Run apt update
      run: sudo apt update
    - name: Install LibELF
      run: sudo apt install -y libelf-dev
    - name: Install LibJansson
      run: sudo apt install -y libjansson-dev 
    - name: Install GLibC Developemental Files and Headers
      run: sudo apt install -y libc6-dev
    - name: Install LLVM
      run: sudo apt install -y llvm
    - name: Install LibXDP Depedencies
      run: sudo apt install -y libpcap-dev m4 gcc-multilib linux-tools-$(uname -r)
    - name: Make and install LibXDP
      run: make libxdp
    - name: Make project
      run: make
    - name: Install project
      run: sudo make install
    - name: Store build artifacts
      uses: actions/upload-artifact@master
      with:
        name: build-output
        path: build/xdpfw
